# Generated by Django 4.0.6 on 2022-07-07 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_size', models.CharField(max_length=24, verbose_name='Original size')),
                ('converted_size', models.CharField(max_length=24, verbose_name='Converted size')),
                ('original_img', models.FileField(upload_to='originals/%m/%d/', verbose_name='Original size')),
                ('converted_img', models.FileField(upload_to='converted/%m/%d/', verbose_name='Converted size')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.CreateModel(
            name='ConvertRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='converter.file')),
            ],
            options={
                'verbose_name': 'Convert request',
                'verbose_name_plural': 'Convert requests',
            },
        ),
    ]
