# Generated by Django 4.0.6 on 2022-07-07 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='convertrequest',
            options={'ordering': ['created_at'], 'verbose_name': 'Запрос на конвертацию', 'verbose_name_plural': 'Запросы на конвертацию'},
        ),
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['original_size'], 'verbose_name': 'Файл', 'verbose_name_plural': 'Файлы'},
        ),
    ]
